version: '3.8'
name: trip-rover
services:
  postgres:
    image: postgres:16.4-alpine
    container_name: trip-rover-postgres-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/trip-rover

  redis:
    image: redis:7.4.0-alpine
    container_name: trip-rover-redis
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: trip-rover
    ports:
      - "6379:6379"
    command: redis-server --requirepass "123456"
    volumes:
      - redis-data:/trip-rover

volumes:
  postgres-data:
  redis-data:
