version: '3.8'
name: trip-rover
services:
  postgres:
    image: postgres:16.4-alpine
    container_name: trip-rover-postgres-db
    env_file:
      - ${ENV_FILE}
    command: >
      postgres
      -c wal_level=logical
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4.0-alpine
    container_name: trip-rover-redis
    env_file:
      - ${ENV_FILE}
    ports:
      - "6379:6379"
    command: redis-server --requirepass $$REDIS_PASSWORD
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:8.10.4
    container_name: trip-rover-elasticsearch
    env_file:
      - ${ENV_FILE}
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -u $$ELASTIC_USERNAME:$$ELASTIC_PASSWORD -f http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  zookeeper:
    image: debezium/zookeeper:2.5
    container_name: trip-rover-zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    volumes:
      - zookeeper-data:/zookeeper/data
      - zookeeper-logs:/zookeeper/txns
    healthcheck:
      test: /zookeeper/bin/zkServer.sh print-cmd || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: debezium/kafka:2.5
    container_name: trip-rover-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
    volumes:
      - kafka-data:/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/kafka/bin/kafka-topics.sh --bootstrap-server=localhost:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 5

  debezium:
    build:
      context: ./docker/debezium
      dockerfile: Dockerfile
    container_name: trip-rover-debezium
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      GROUP_ID: trip-rover
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      STATUS_STORAGE_REPLICATION_FACTOR: "1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/connectors"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres-data:
    name: trip-rover-postgres-data
  redis-data:
    name: trip-rover-redis-data
  elasticsearch-data:
    name: trip-rover-elasticsearch-data
  zookeeper-data:
    name: trip-rover-zookeeper-data
  zookeeper-logs:
    name: trip-rover-zookeeper-logs
  kafka-data:
    name: trip-rover-kafka-data
  debezium-plugins:
    name: trip-rover-debezium-plugins

