spring:
  config:
    import: file:.env[.properties]
  application:
    name: TripRover
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 10

logging:
  level:
    org.springframework.security: trace

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 405704196940-sf6a4gn0mairbdaib9h9fvg4bo0a61tp.apps.googleusercontent.com
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#            scope:
#              - email
#              - profile