spring:
  application:
    name: TripRover
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trip_rover
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 10
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 405704196940-sf6a4gn0mairbdaib9h9fvg4bo0a61tp.apps.googleusercontent.com
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#            scope:
#              - email
#              - profile
logging:
  level:
    org.springframework.security: trace